// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn2MQoJ-jnwwaiBfj1sL20fSUgO_Swhhc',
    appId: '1:1000242128101:web:944c4952c8a06d4b93200c',
    messagingSenderId: '1000242128101',
    projectId: 'auth-2e72c',
    authDomain: 'auth-2e72c.firebaseapp.com',
    storageBucket: 'auth-2e72c.appspot.com',
    measurementId: 'G-J7S776FV4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw2XwUb3YTOb7dUJRvYQMmRqC4WpGHqLE',
    appId: '1:1000242128101:android:fd0720cef28d385c93200c',
    messagingSenderId: '1000242128101',
    projectId: 'auth-2e72c',
    storageBucket: 'auth-2e72c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFZiGdaUy9imVSzIhfQ3XKmR_vkvrZvg',
    appId: '1:1000242128101:ios:d4a0be81afb87db393200c',
    messagingSenderId: '1000242128101',
    projectId: 'auth-2e72c',
    storageBucket: 'auth-2e72c.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYFZiGdaUy9imVSzIhfQ3XKmR_vkvrZvg',
    appId: '1:1000242128101:ios:d4a0be81afb87db393200c',
    messagingSenderId: '1000242128101',
    projectId: 'auth-2e72c',
    storageBucket: 'auth-2e72c.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn2MQoJ-jnwwaiBfj1sL20fSUgO_Swhhc',
    appId: '1:1000242128101:web:4ce71f53ca2e262293200c',
    messagingSenderId: '1000242128101',
    projectId: 'auth-2e72c',
    authDomain: 'auth-2e72c.firebaseapp.com',
    storageBucket: 'auth-2e72c.appspot.com',
    measurementId: 'G-965BNP8Q0E',
  );

}